// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imzlzufdujhcbebibgpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imltemx6dWZkdWpoY2JlYmliZ3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjUyNzMsImV4cCI6MjA2MjEwMTI3M30.R3cQ-nCSUOSsVmcVxG-xZJuD8HZxoi2GYlZl5GLB4EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});